version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs-tutorial
    ports: 
      - "1234:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/opt/app
